#ifndef ENUMS_H
#define ENUMS_H
enum ENCODINGS{
	DETECT_ENCODING=0,
	ISO_8859_1_ENCODING=1,
	UCS2_ENCODING=2,
	UTF8_ENCODING=3,
	SJIS_ENCODING=4
};

enum METHODS{
	NO_ALPHA=0,
	CLASSIC_METHOD=1,
	ALPHA_METHOD=2
};

enum ENCRYPTION{
	NO_ENCRYPTION=0,
	XOR84_ENCRYPTION=1,
	VARIABLE_XOR_ENCRYPTION=2,
	TRANSFORM_THEN_XOR84_ENCRYPTION=3
};

enum INTERPRETER_MODES{
	DEFINE,
	NORMAL,
};
#endif
